# Site Info
title:
tagline: '훈이의 블로그'
description:
baseurl: ""
url: http://jeonghoon1107.github.io
logo: ''

# Site configurations
plugins:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 7
paginate_path: '/post/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: 훈이
  description: Software Engineer
  gravatar: # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/%EC%A0%95%ED%9B%88-%EC%A1%B0-57ab01120/
    github:    https://github.com/jeonghoon1107
    facebook:  https://www.facebook.com/profile.php?id=100003606682273

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Post:
    - '/post/'
    # - { spring: '/post/spring/' }
    # - { javascript: '/post/javascript/' }
  About:
    - '/about/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption:

# Puglins
# mathjax: true # whether support mathjax
# google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
# disqus_short_name: 'your_short_name' # leave blank if you don't want disqus
